### ISSUE TITLE
hard coding for `alpha` argument

### ISSUE THREAD

**Issue by julia-wrobel** [Ghoshlab/marr#3]
Both the `Marr` and `MarrProc` functions have the `alpha` function argument hard-coded in the body of the function. FYI~

**Comment by tghosh30** [comment]
Thanks, Julia. I've fixed the hard-coding issue in line 53 (MarrProc.R) and line 93 (Marr.R).

**Comment by tghosh30** [comment]
I'm closing this issue.

**Comment by julia-wrobel** [comment]
Awesome, thanks Tushar!



On Dec 21, 2020, at 5:19 PM, Tusharkanti Ghosh <notifications@github.com<mailto:notifications@github.com>> wrote:



I'm closing this issue.
